import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { SignetContextProvider } from "../components/SignetConnector"
import { AccountManager } from "./context/AccountManager"
import { ApiManager } from "./context/ApiManager"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApiManager>
          <AccountManager>{children}</AccountManager>
        </ApiManager>
      </body>
    </html>
  )
}
